In [25]:
import pandas

url = "https://docs.google.com/spreadsheets/d/1d18VYLtcfhTkFtd1oszOHW3EQOqReMnchzgtd--FdBA/gviz/tq?tqx=out:csv&sheet=Officer"
data = pandas.read_csv(url)

In [26]:
data

,Scale,DESIG,NAME,Post Code,W.E.F.,Remarks,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,HAG,PFA,AMAR KUMAR SINHA,02NC3P002,08-08-2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HAG,FA&CAO/T&Capex,HAMIM AHMED,02NC3P001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SAG,FA&CAO/G/PRYJ,ADITYA JOSHI,02NC4P001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SAG,FA&CAO/F&B/PRYJ,GAUTAM JAIN,02NC4P002,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SAG,FA&CAO/IT/PRYJ,*Temporarily transferred to General Admin,02NC4P003,NaN,*Temporarily transferred to General Admin depa...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Group-B,AFA/Coaching/PRYJ,SUNIL KUMAR PANDEY,02NC8W014,04-11-2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Group-B,AFA/GOODS/PRYJ,NEELAM KUMAR,02NC8W015,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Group-B,AFA/C/PRYJ,BRAJENDRA BAHADUR,02NC8W016,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Group-B,AFA/Const-II/PRYJ,SUJEET KUMAR,02NC8W017,01-11-2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Group-B,AFA/PU/PRYJ\n (used as ADFM-III/PRYJ),RAJEEV KUMAR,02NC8W018,01-11-2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data[(data["DESIG"] == "SSO") & (data["NAME"] != "VACANT")].count()["NAME"]

45

In [27]:
data['W.E.F.'] = pandas.to_datetime(data['W.E.F.'], format='%d-%m-%Y')

In [28]:
data

,Scale,DESIG,NAME,Post Code,W.E.F.,Remarks,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,HAG,PFA,AMAR KUMAR SINHA,02NC3P002,2024-08-08,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HAG,FA&CAO/T&Capex,HAMIM AHMED,02NC3P001,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SAG,FA&CAO/G/PRYJ,ADITYA JOSHI,02NC4P001,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SAG,FA&CAO/F&B/PRYJ,GAUTAM JAIN,02NC4P002,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SAG,FA&CAO/IT/PRYJ,*Temporarily transferred to General Admin,02NC4P003,NaT,*Temporarily transferred to General Admin depa...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Group-B,AFA/Coaching/PRYJ,SUNIL KUMAR PANDEY,02NC8W014,2024-11-04,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Group-B,AFA/GOODS/PRYJ,NEELAM KUMAR,02NC8W015,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Group-B,AFA/C/PRYJ,BRAJENDRA BAHADUR,02NC8W016,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Group-B,AFA/Const-II/PRYJ,SUJEET KUMAR,02NC8W017,2024-11-01,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Group-B,AFA/PU/PRYJ\n (used as ADFM-III/PRYJ),RAJEEV KUMAR,02NC8W018,2024-11-01,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
import datetime
today = datetime.datetime.now()
x = pandas.to_datetime(data["W.E.F."][0], format='%d-%m-%Y')
today - x

Timedelta('148 days 16:17:51.225818')

In [13]:
data["TIME"] = today-data["W.E.F."]

TypeError: Addition/subtraction of integers and integer-arrays with Timestamp is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`

In [29]:
for x in list(data["W.E.F."]):
    print(today-x)

148 days 16:17:51.225818
NaT
NaT
NaT
NaT
NaT
NaT
59 days 16:17:51.225818
757 days 16:17:51.225818
242 days 16:17:51.225818
358 days 16:17:51.225818
NaT
NaT
757 days 16:17:51.225818
NaT
756 days 16:17:51.225818
756 days 16:17:51.225818
756 days 16:17:51.225818
756 days 16:17:51.225818
205 days 16:17:51.225818
239 days 16:17:51.225818
611 days 16:17:51.225818
239 days 16:17:51.225818
850 days 16:17:51.225818
186 days 16:17:51.225818
NaT
NaT
NaT
479 days 16:17:51.225818
NaT
NaT
240 days 16:17:51.225818
NaT
NaT
NaT
NaT
NaT
NaT
NaT
NaT
NaT
NaT
NaT
NaT
884 days 16:17:51.225818
NaT
NaT
NaT
NaT
63 days 16:17:51.225818
NaT
186 days 16:17:51.225818
850 days 16:17:51.225818
NaT
NaT
NaT
NaT
612 days 16:17:51.225818
884 days 16:17:51.225818
NaT
60 days 16:17:51.225818
NaT
NaT
63 days 16:17:51.225818
63 days 16:17:51.225818

In [19]:
def convert_to_datetime(df):
    result = []
    for index, row in df.iterrows():
        try:
            result.append(pandas.to_datetime(row["W.E.F."], format='%d-%m-%Y'))
        except:
            result.append(0)
    return result
data['W.E.F.'] = convert_to_datetime(data)

,Scale,DESIG,NAME,Post Code,W.E.F.,Remarks,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,HAG,PFA,AMAR KUMAR SINHA,02NC3P002,2024-08-08 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HAG,FA&CAO/T&Capex,HAMIM AHMED,02NC3P001,2024-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SAG,FA&CAO/G/PRYJ,ADITYA JOSHI,02NC4P001,2024-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SAG,FA&CAO/F&B/PRYJ,GAUTAM JAIN,02NC4P002,2024-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SAG,FA&CAO/IT/PRYJ,*Temporarily transferred to General Admin,02NC4P003,0,*Temporarily transferred to General Admin depa...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Group-B,AFA/Coaching/PRYJ,SUNIL KUMAR PANDEY,02NC8W014,2024-11-04 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Group-B,AFA/GOODS/PRYJ,NEELAM KUMAR,02NC8W015,2022-12-29 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Group-B,AFA/C/PRYJ,BRAJENDRA BAHADUR,02NC8W016,2021-06-18 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Group-B,AFA/Const-II/PRYJ,SUJEET KUMAR,02NC8W017,2024-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Group-B,AFA/PU/PRYJ\n (used as ADFM-III/PRYJ),RAJEEV KUMAR,02NC8W018,2024-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
strength = data[data["NAME"] != "VACANT"]["DESIG"].value_counts()

In [57]:
for desig, item in strength.items():
    print(desig, item)

JAA 54
SSO 45
AA 31
AC 21

In [20]:
data['W.E.F.']

0     2024-08-08 00:00:00
1     2024-06-29 00:00:00
2     2024-06-28 00:00:00
3     2024-06-28 00:00:00
4                       0
             ...
60    2024-11-04 00:00:00
61    2022-12-29 00:00:00
62    2021-06-18 00:00:00
63    2024-11-01 00:00:00
64    2024-11-01 00:00:00
Name: W.E.F., Length: 65, dtype: object

In [76]:
import datetime
onroll = data[data["NAME"] != "VACANT"]
today = datetime.datetime.now()
onroll["TIME"] = today-onroll["W.E.F."]
onroll["TIME"] = [time.days/365 for time in onroll["TIME"]]
# msg = "Age-wise breakup of staff is as under:\n"
# due1 = onroll[(onroll["TIME"] > 3) & (onroll["TIME"] < 4)]
# due2 = onroll[(onroll["TIME"] > 4) & (onroll["TIME"] < 5)]
# due3 = onroll[onroll["TIME"] > 5]
# print(due1)
# for index, row in due1.iterrows():
#         msg += f"{row['NAME']}, {row['DESIG']}: {round(row['TIME'], 1)} years"
# msg

C:\Users\User\AppData\Local\Temp\ipykernel_16868\2315147642.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  onroll["TIME"] = today-onroll["W.E.F."]
C:\Users\User\AppData\Local\Temp\ipykernel_16868\2315147642.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  onroll["TIME"] = [time.days/365 for time in onroll["TIME"]]

In [77]:
onroll

,SN,SECTION,NAME,DESIG,W.E.F.,S/NS,REMARKS,TIME
0,1,PFA/CELL,A.K.SRIVASTAVA,SSO,2019-08-30,NS,NaN,5.328767
1,2,PFA/CELL,PRABEER RANJAN SARKAR,JAA,2023-08-07,NS,NaN,1.389041
2,3,FA/G CELL,SANJEEV KUMAR YADAV,JAA,2024-09-13,NS,NaN,0.284932
3,4,FA/T & CM CELL,A P DUBEY,AA,2023-12-01,NS,NaN,1.071233
4,5,FA/WS CELL,Manoj Kumar Verma,AA,2023-09-13,NS,NaN,1.287671
...,...,...,...,...,...,...,...,...
171,172,AUDIT,SANJAY KUMAR,AA,2022-07-08,NS,NaN,2.471233
172,173,AUDIT,SANJAY KUMAR SINGH,AA,2024-01-17,NS,NaN,0.942466
173,174,AUDIT,AKHILESH KUMAR DIXIT,JAA,2023-04-07,NS,NaN,1.723288
174,175,AUDIT,ANUPRIYA PANDEY,JAA,2023-05-31,NS,NaN,1.575342
177,178,IT,PANKAJ GUPTA,SSO,2022-07-01,NS,NaN,2.490411

In [80]:
onroll.sort_values(['TIME'], ascending=False)

,SN,SECTION,NAME,DESIG,W.E.F.,S/NS,REMARKS,TIME
52,53,ADM GAZ,AJAY TRIPATHI,JAA,1900-01-17,NS,NaN,125.024658
166,167,FINANCE,AFTAB ALAM,SSO,2019-07-17,NS,Order issued for Books IV,5.449315
0,1,PFA/CELL,A.K.SRIVASTAVA,SSO,2019-08-30,NS,NaN,5.328767
33,34,ENG,KU. NEELAM,AA,2019-09-09,NS,NaN,5.301370
50,51,ADM GAZ,LALA RANJAY KUMAR AMBASTA,SSO,2019-12-31,NS,NaN,4.991781
...,...,...,...,...,...,...,...,...
165,166,FINANCE,PANKAJ KUMAR,SSO,2024-10-25,NS,NaN,0.169863
70,71,PENSION,RAMJOT KUMAR AZAD,SSO,2024-10-25,S,NaN,0.169863
129,130,GENERAL,PANKAJ KUMAR NIRALA,SSO,2024-12-06,NS,NaN,0.054795
78,79,PDS,DEVRAJ ROY,SSO,2024-12-09,NS,NaN,0.046575
164,165,FINANCE,ARUN KUMAR PANDIT,SSO,2024-12-10,NS,NaN,0.043836

In [79]:
onroll

,SN,SECTION,NAME,DESIG,W.E.F.,S/NS,REMARKS,TIME
0,1,PFA/CELL,A.K.SRIVASTAVA,SSO,2019-08-30,NS,NaN,5.328767
1,2,PFA/CELL,PRABEER RANJAN SARKAR,JAA,2023-08-07,NS,NaN,1.389041
2,3,FA/G CELL,SANJEEV KUMAR YADAV,JAA,2024-09-13,NS,NaN,0.284932
3,4,FA/T & CM CELL,A P DUBEY,AA,2023-12-01,NS,NaN,1.071233
4,5,FA/WS CELL,Manoj Kumar Verma,AA,2023-09-13,NS,NaN,1.287671
...,...,...,...,...,...,...,...,...
171,172,AUDIT,SANJAY KUMAR,AA,2022-07-08,NS,NaN,2.471233
172,173,AUDIT,SANJAY KUMAR SINGH,AA,2024-01-17,NS,NaN,0.942466
173,174,AUDIT,AKHILESH KUMAR DIXIT,JAA,2023-04-07,NS,NaN,1.723288
174,175,AUDIT,ANUPRIYA PANDEY,JAA,2023-05-31,NS,NaN,1.575342
177,178,IT,PANKAJ GUPTA,SSO,2022-07-01,NS,NaN,2.490411

In [81]:
onroll["NAME"].count()

151